apiVersion: v1
kind: Service
metadata:
  name: neo4jcontainer-standalone-svc
  labels:
    app: neo4jcontainer-standalone-app
spec:
  ports:
    - port: 17474
      targetPort: 7474
      name: browser
    - port: 17687
      targetPort: 7687
      name: bolt
  #clusterIP: None
  selector:
    app: neo4jcontainer-standalone-app
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4jcontainer-standalone-pv-claim
  labels:
    app: neo4jcontainer-standalone-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4jcontainer-standalone-app
spec:
  serviceName: "neo4jcontainer-standalone-svc"
  replicas: 1
  selector:
    matchLabels:
      app: neo4jcontainer-standalone-app
  template:
    metadata:
      labels:
        app: neo4jcontainer-standalone-app
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 65532
      containers:
        - name: neo4jcontainer-standalone-instance
          image: neo4j-docker:enterprise
          imagePullPolicy: Never
          env:
            - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
              value: "yes"
            - name: NEO4J_dbms_connector_bolt_advertised__address
              value: ":17687"
          ports:
            - containerPort: 5000
              name: tcp-discovery
            - containerPort: 6000
              name: tcp-tx
            - containerPort: 7000
              name: tcp-raft
            - containerPort: 7474
              name: tcp-browser
            - containerPort: 7687
              name: tcp-bolt
          resources:
            requests:
              memory: 512Mi
#              cpu: 2.0
            limits:
              memory: 1Gi
#              cpu: 4.0
          volumeMounts:
            - name: neo4jcontainer-standalone-datadir
              mountPath: "/data"
          readinessProbe:
            initialDelaySeconds: 60
            failureThreshold: 3
            timeoutSeconds: 2
            periodSeconds: 10
            tcpSocket:
              port: 7687
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
            tcpSocket:
              port: 7687
      volumes:
        - name: neo4jcontainer-standalone-datadir
          persistentVolumeClaim:
            claimName: neo4jcontainer-standalone-pv-claim
